#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0-only

set -e -o nounset -o pipefail

if [[ -z ${SIMPLE_VERSION:-} ]]; then
	version_extra='g${builtins.substring 0 9 src.rev}'
fi

if [[ -n ${NUG_DEBUG:=} ]]; then
	set -x
fi

for file; do
	(
		branch=$(sed -n 's|^\s*#branch@date: \([^@]\+\)@.*|\1|p' $file)
		commitish=$branch
		if [[ $file == *@*@* ]]; then
			commitish=${file##*@}
			file=${file%@*}
			branch=${file#*@}
			file=${file%%@*}
		elif [[ $file == *@* ]]; then
			commitish=${file#*@}
			branch=$commitish
			file=${file%%@*}
		fi

		owner=$(awk '/owner =/ {print $3}' "$file" | sed -E 's|"(.*)";|\1|')
		repo=$(awk '/repo =/ {print $3}' "$file" | sed -E 's|"?([^"]*)"?;|\1|')
		if [[ $repo == *pname* ]]; then
			repo=$(awk '/pname =/ {print $3}' "$file" | sed 's|"\(.*\)";|\1|')
		fi

		url="https://api.github.com/repos/$owner/$repo"
		if [[ -z ${branch:-} ]]; then
			branch=$(gh api "$url" --jq '.default_branch')
			commitish=$branch
		fi
		url+=/commits/$commitish

		commit=$(gh api "$url" --jq "{sha, commit}")
		commit_id=$(jq -r .sha <<<"$commit")
		commit_date=$(jq -r .commit.committer.date <<<"$commit")
		version=$(date +'unstable-%Y-%m-%d' --date="$commit_date")
		sha256=$(nix-prefetch-url --quiet --unpack "https://github.com/$owner/$repo/archive/$commit_id.tar.gz" 2>/dev/null)
		echo "file=$file"
		sed -i \
			-e "/rev =/ s|\".*\"|\"$commit_id\"|" \
			-e "/sha256 =/ s|\".*\"|\"$sha256\"|" \
			-e "/version =/ s|\".*\"|\"${version}${version_extra:-}\"|" \
			"$file"
		if grep -q '^\s*#branch@date:' "$file"; then
			commit_date=$(date +%Y-%m-%d --date="$commit_date")
			sed -i -e "/^\s*#branch@date:/ s|:.*|: $branch@$commit_date|" "$file"
		fi
	) &
done
wait
